### ISSUE TITLE
Opening an authenticated websocket

### ISSUE THREAD

**Issue by petar** [preichenberger/go-coinbasepro#101]
Coinbase Pro advises using authenticated websockets for some extra detail in the feed.
The main doc has an example of opening an unathenticated websocket. Is there a facility
to open an authenticated one, using API Key, API Secret and API Phassphrase?

Thanks.

**Comment by sknr** [comment]
Hi petar,

in order to receive the [user-channel](https://docs.pro.coinbase.com/?python#the-user-channel) for example, you need to sign the `subscribeMessage` first like and then send the `subscribeMessageSigned`. See the example below:

```
var wsDialer ws.Dialer
wsConn, _, err := wsDialer.Dial("wss://ws-feed.pro.coinbase.com", nil)
if err != nil {
	println(err.Error())
}

subscribeMessage := coinbasepro.Message{
	Type:      "subscribe",
	Channels: []coinbasepro.MessageChannel{
		{
			Name: "heartbeat",
			ProductIds: []string{
				"BTC-USD",
			},
		},
		{
			Name: "user",
			ProductIds: []string{
				"BTC-USD",
			},
		},
	},
}

subscribeMessageSigned, err = subscribeMessage.Sign(c.Secret, c.Key, c.Passphrase)
// Handle err

if err := wsConn.WriteJSON(subscribeMessageSigned); err != nil {
	println(err.Error())
}   
```

**Comment by petar** [comment]
Thank you!
