### ISSUE TITLE
Coinbase prime API calls

### ISSUE THREAD

**Issue by sapnasalaskar** [preichenberger/go-coinbasepro#68]
Hi @preichenberger 

I would like to report an issue wherein the new prime coinbase api endpoints have not been integrated in the repo yet. Will you be integrating them? 
Reference: https://docs.prime.coinbase.com/#introduction
Awaiting your reply, thank you!

**Comment by preichenberger** [comment]
I'm not too familiar with coinbase prime, a quick glance at the docs seems like it's similar to coinbase pro, what are the notable differences?
