### ISSUE TITLE
Unify configuration for test environment

### ISSUE THREAD

**Issue by lukaszraczylo** [preichenberger/go-coinbasepro#75]
It would be great to unify configuration for both production and sandbox environments.
It's a little bit confusing and requires additional coding to set/read appropriate environment variables.

**Comment by lukaszraczylo** [comment]
Library currently requires two different sets of environment variables:

Production environment:

```COINBASE_SECRET
COINBASE_KEY
COINBASE_PASSPHRASE```

And following for sandbox environment:

```
TEST_COINBASE_SECRET
TEST_COINBASE_KEY
TEST_COINBASE_PASSPHRASE
```

Setting them up is slightly different and it would be easier to leave only

```COINBASE_SECRET
COINBASE_KEY
COINBASE_PASSPHRASE```

and add additional flag COINBASE_SANDBOX, with default being false to switch between the environments without any additional code changes required. In this case I mean "NewClient" vs "NewTestClient".

**Comment by preichenberger** [comment]
Added COINBASE_PRO_SANDBOX here https://github.com/preichenberger/go-coinbasepro/commit/7f1a157f8a87089fb5d7ab873c98d0dc52f79046
