### ISSUE TITLE
json: cannot unmarshal object into Go struct field Message.changes of type []string

### ISSUE THREAD

**Issue by w1t** [preichenberger/go-coinbasepro#83]
Hello

Philip, I received the error in the subject when I run the following code.

I found if I removed the following code in message.go it works fine. 

Do you know why?
-----your source code -----------
func (e *SnapshotChange) UnmarshalJSON(data []byte) error {
  	var entry []string

  	if err := json.Unmarshal(data, &entry); err != nil {
  		return err
  	}

  	e.Side = entry[0]
  	e.Price = entry[1]
  	e.Size = entry[2]

  	return nil
  }
----------my testing code -------
package main
import (
 "fmt"
"log"
"encoding/json"
coinbasepro "github.com/preichenberger/go-coinbasepro"

  )
 func check(e error) {
      if e != nil {
        log.Fatal(e)
      }
  }

func main(){

//the messageJson is captured from the coinbase pro ws feed. 

  messageJson := `{
   "type": "l2update",
   "product_id": "ETH-USD",
   "product_ids": null,
   "trade_id": 0,
   "order_id": "",
   "client_oid": "",
   "sequence": 0,
   "maker_order_id": "",
   "taker_order_id": "",
   "time": "2019-04-26T20:34:02.674Z",
   "remaining_size": "",
   "new_size": "",
   "old_size": "",
   "size": "",
   "price": "",
   "side": "",
   "reason": "",
   "order_type": "",
   "funds": "",
   "new_funds": "",
   "old_funds": "",
   "message": "",
   "changes": [
    {
     "Side": "sell",
     "Price": "151.44000000",
     "Size": "0.11"
    }
   ],
   "last_size": "",
   "best_bid": "",
   "best_ask": "",
   "channels": null,
   "user_id": "",
   "profile_id": "",
   "last_trade_id": 0
  }`

message := coinbasepro.Message {}

err := json.Unmarshal([]byte(messageJson), &message)
 check(err)
 fmt.Println(message)

}

**Comment by preichenberger** [comment]
Can you provide the endpoint where you're getting that response? According to the docs https://docs.pro.coinbase.com/#the-level2-channel, changes should be returned as array i.e ["sell", "151.44000000", "0.11"] not an object. The code your "removed" is the code to map the array to the struct fields.

**Comment by w1t** [comment]
Thank you point it out. You are correct. I marshaled the message in a file and read it back. it is saved as a json object. I close this issue.
