### ISSUE TITLE
Candles returns incomplete data

### ISSUE THREAD

**Issue by utdrmac** [preichenberger/go-coinbasepro#86]
According to the [documentation](https://docs.pro.coinbase.com/#get-historic-rates),
>  Historical rate data may be incomplete. No data is published for intervals where there are no ticks.

When I call GetHistoricRate() on a 5 minute interval, I expect 72 candles over a 6hr period (6hr * 60m = 360m / 5m = 72 intervals)
But because of the above notation, there are "holes" in the returned data. How do you handle these holes? Do you just copy the previous interval or assign all 0's to HLOC?

**Comment by preichenberger** [comment]
The API client doesn't do any special handling of "holes". The only transformation is mapping the historic data (which is in array form) to a struct: https://godoc.org/github.com/preichenberger/go-coinbasepro#HistoricRate

**Comment by utdrmac** [comment]
@preichenberger I understand that the API does not handle the holes. I'm asking how I should handle them in my application? If I simply plot the data returned, my candlestick charts will be incomplete. How should I fill in the holes?

**Comment by preichenberger** [comment]
Depends on what you need for your app. Previous interval if a bucket is missing seems like a reasonable approach.

**Comment by utdrmac** [comment]
Do you know if this is how pro.coinbase.com fills in the holes?

**Comment by utdrmac** [comment]
If pro.coinbase.com is using the same API for their GUI, how does their GUI handle the holes?

**Comment by preichenberger** [comment]
I don't know, you could look at the javascript code on the Coinbase Pro site. Closing this for now, since this request is outside the scope of what this library supports.
